# Generated by Django 5.1.2 on 2024-12-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('department_head', 'Department Head'), ('executive', 'Executive')], default='employee', max_length=50),
        ),
    ]
