# Generated by Django 5.1.2 on 2024-12-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('department_head', 'Department Head'), ('executive', 'Executive'), ('admin', 'Admin')], default='employee', max_length=50),
        ),
    ]
