# Generated by Django 5.1.2 on 2024-11-19 22:53

import django.db.models.deletion
import handbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.TextField()),
            ],
            options={
                'verbose_name': 'Definition',
                'verbose_name_plural': 'Definitions',
            },
        ),
        migrations.CreateModel(
            name='PolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('number', models.CharField(max_length=10, unique=True, validators=[handbook.models.validate_section_number])),
            ],
            options={
                'verbose_name': 'Policy Section',
                'verbose_name_plural': 'Policy Sections',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.CharField(editable=False, max_length=10, unique=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('policy_statements', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('procedures', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=10)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('review_period', models.CharField(blank=True, max_length=50, null=True)),
                ('definitions', models.ManyToManyField(blank=True, related_name='policies', to='handbook.definition')),
                ('policy_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='accounts.department')),
                ('related_policies', models.ManyToManyField(blank=True, related_name='related_to', to='handbook.policy')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='handbook.policysection')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='PolicyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='handbook.policy')),
            ],
            options={
                'verbose_name': 'Policy Request',
                'verbose_name_plural': 'Policy Requests',
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_steps', to='handbook.policy')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
