# Generated by Django 5.1.2 on 2024-11-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='policyrequest',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policyrequest',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
