# Generated by Django 5.1.2 on 2024-11-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_remove_policyrequest_name_policyrequest_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policyrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
