# Generated by Django 5.1.2 on 2024-11-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_procedurestep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'verbose_name': 'Definition', 'verbose_name_plural': 'Definitions'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='policyrequest',
            options={'verbose_name': 'Policy Request', 'verbose_name_plural': 'Policy Requests'},
        ),
        migrations.AlterModelOptions(
            name='policysection',
            options={'verbose_name': 'Policy Section', 'verbose_name_plural': 'Policy Sections'},
        ),
    ]
