# Generated by Django 5.1.2 on 2024-11-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_alter_policyrequest_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrequest',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policyrequest',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
