# Generated by Django 5.1.2 on 2024-11-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_alter_policyrequest_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='procedurestep',
            unique_together={('policy', 'step_number')},
        ),
    ]
