# Generated by Django 5.1.2 on 2024-11-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0006_remove_policy_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='review_period',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually'), ('Bi-Annually', 'Bi-Annually'), ('Biennially', 'Biennially')], help_text='Select the review period for this policy.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='step_number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
