# Generated by Django 5.1.2 on 2024-11-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0009_alter_procedurestep_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedurestep',
            options={'ordering': ['step_number']},
        ),
        migrations.AlterUniqueTogether(
            name='procedurestep',
            unique_together={('policy', 'step_number')},
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='procedurestep',
            name='order',
        ),
    ]
