# Generated by Django 5.1.2 on 2024-12-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0012_policyapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='compliance_impact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='financial_impact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='operational_impact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='technology_impact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policyapprovalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revision_needed', 'Revision Needed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
