# Generated by Django 5.1.2 on 2024-12-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0013_policy_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
