# Generated by Django 5.1.2 on 2024-12-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0014_policyapprovalrequest_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyapprovalrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='policyapprovalrequest',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='policyapprovalrequest',
            name='compliance_impact',
        ),
        migrations.RemoveField(
            model_name='policyapprovalrequest',
            name='financial_impact',
        ),
        migrations.RemoveField(
            model_name='policyapprovalrequest',
            name='operational_impact',
        ),
        migrations.RemoveField(
            model_name='policyapprovalrequest',
            name='technology_impact',
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='proposed_policy_statements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='proposed_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='proposed_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='proposed_scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='proposed_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
