# Generated by Django 5.1.2 on 2024-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0015_alter_policyapprovalrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='proposed_definitions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='proposed_procedure_steps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='proposed_related_policies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
