# Generated by Django 5.1.2 on 2024-12-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0016_policyapprovalrequest_proposed_definitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyapprovalrequest',
            name='proposed_definitions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='policyapprovalrequest',
            name='proposed_procedure_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='policyapprovalrequest',
            name='proposed_related_policies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
