# Generated by Django 5.1.2 on 2024-12-03 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0017_alter_policyapprovalrequest_proposed_definitions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='request_type',
            field=models.CharField(choices=[('new', 'New Policy'), ('edit', 'Edit Policy'), ('archive', 'Archive Policy')], default='edit', max_length=10),
        ),
        migrations.AlterField(
            model_name='policyapprovalrequest',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='handbook.policy'),
        ),
    ]
