# Generated by Django 5.1.2 on 2024-12-04 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
        ('handbook', '0018_policyapprovalrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='policy_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='proposed_review_period',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually'), ('Bi-Annually', 'Bi-Annually'), ('Biennially', 'Biennially')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='handbook.policysection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
