# Generated by Django 5.1.2 on 2024-12-04 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0021_archivedpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapprovalrequest',
            name='archived_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='handbook.archivedpolicy'),
        ),
    ]
