# Generated by Django 5.1.2 on 2024-12-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0022_policyapprovalrequest_archived_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpolicy',
            name='elated_policies',
        ),
        migrations.AlterField(
            model_name='archivedpolicy',
            name='related_policies',
            field=models.ManyToManyField(blank=True, related_name='archived_related_policies', to='handbook.policy'),
        ),
    ]
