# Generated by Django 5.1.2 on 2024-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0023_remove_archivedpolicy_elated_policies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpolicy',
            name='procedure_steps',
        ),
        migrations.AddField(
            model_name='archivedpolicy',
            name='procedure_steps_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
