# Generated by Django 5.1.2 on 2024-12-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0024_remove_archivedpolicy_procedure_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpolicy',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='archived',
        ),
    ]
