# Generated by Django 5.1.2 on 2024-12-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0026_definition_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedpolicy',
            options={'verbose_name': 'Archived Policy', 'verbose_name_plural': 'Archived Policies'},
        ),
        migrations.AlterModelOptions(
            name='policyapprovalrequest',
            options={'verbose_name': 'Policy Approval Request', 'verbose_name_plural': 'Policy Approval Requests'},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='published',
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
