# Generated by Django 5.1.2 on 2024-12-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0029_alter_policy_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolicyRequest',
            new_name='PolicyFeedback',
        ),
        migrations.AlterModelOptions(
            name='policyfeedback',
            options={'verbose_name': 'Policy Feedback', 'verbose_name_plural': 'Policy Feedback'},
        ),
    ]
